In [5]:
import cv2
import numpy as np

import utils.estimate_homography as util

stable, unstable = util.get_toy()
h = util.find_H(stable, unstable)

In [6]:
h

array([[ 8.86785691e-01, -7.79721040e-02,  1.58171691e+02],
       [ 4.43431992e-03,  9.47755851e-01, -1.36388707e+01],
       [-9.21245726e-05, -2.20078809e-05,  1.00000000e+00]])

In [7]:
np.matmul(h.transpose(), h)

array([[ 7.86408533e-01, -6.49418915e-02,  1.40203821e+02],
       [-6.49418915e-02,  9.04320802e-01, -2.52593210e+01],
       [ 1.40203821e+02, -2.52593210e+01,  2.52053026e+04]])

In [8]:
np.matmul(h.transpose(), h) - np.identity(3)

array([[-2.13591467e-01, -6.49418915e-02,  1.40203821e+02],
       [-6.49418915e-02, -9.56791979e-02, -2.52593210e+01],
       [ 1.40203821e+02, -2.52593210e+01,  2.52043026e+04]])